### ISSUE TITLE
Magisk installation fails

### ISSUE THREAD

**Issue by Megver83** [AXIM0S/gearlock#8]
I tried to install Magisk through Gearlock's Extra misc functions, but I'm always ending up with `Error: Failed to extract magisk.zip`, don't know why, but I suspect it might be because of the APK-flashzip hybrid style of new versions of magisk (maybe an option to choose which version would be good, for some reason in the previous gearlock version I could select a local magisk.zip, but now I'm forced into downloading it). I'm using the latest Gearlock version in BlissOS 11.12 FOSS.

**Comment by AXIM0S** [comment]
https://github.com/AXIM0S/gearlock/commit/45e7831dda7e9294d61087a5f1142c6a6334c978 Fixes this.
